### ISSUE TITLE
Fixed port number

### ISSUE THREAD

**Issue by jon-armstrong** [kevin1024/pytest-httpbin#24]
I'm using pytest-httpbin to test a proxy which needs to know the upstream host and port number it is proxying requests to. Currently, my workaround for this is to grab the url from the httpbin object and dynamically write the proxy config with this information. However, it would be convenient to be able to specify the port number pytest-httpbin runs on so I don't need to do this.

**Comment by kevin1024** [comment]
Sounds useful.  How would this be configured?  pytest-httpbin doesn't have any configuration right now.

**Comment by jon-armstrong** [comment]
I was going to suggest adding port setup in conftest.py, but it looks like that's processed after the built plugins are loaded: http://pytest.org/latest/plugins.html. So, without changing how pytest-httpbin is invoked by default (or adding a separate config), I'm not sure if this is possible.

**Comment by hroncok** [comment]
HTTPBIN_HTTP_PORT and HTTPBIN_HTTPS_PORT environment variables? Might not be super clean, but will be easy to implement.

**Comment by kevin1024** [comment]
works for me.  Happy to merge a PR as long as it includes tests & docs :)

**Comment by hroncok** [comment]
On it.
