### ISSUE TITLE
pypy: server crashes when invalid SSL requests happen

### ISSUE THREAD

**Issue by kevin1024** [kevin1024/pytest-httpbin#25]
When an SSL exception happens in the server, it shouldn't freeze up the server and prevent it from finishing the request (or doing subsequent requests)

**Comment by kevin1024** [comment]
[Added a failing test in a new branch](https://github.com/kevin1024/pytest-httpbin/tree/https-freeze)

**Comment by msabramo** [comment]
Nice sleuthing, @kevin1024 !

**Comment by kevin1024** [comment]
OK, this was a little different than I thought, so I hope it still fixes all the issues.

What was happening is that on pypy, the version of the stdlib doesn't seem to set a timeout for the SSL socket.  So when the validation was failing, it was just hanging.  I manually set a timeout on the socket, and it seems to have fixed the issue.

Please reopen if this didn't solve it, but I can't reproduce the error anymore so it seems to have fixed something!

**Comment by kevin1024** [comment]
fixed in f38a3124465925d9a2cf8d07c43a597f109d11ea (for future reference)
