### ISSUE TITLE
Python3 installation on Windows: "Couldn't find a setup script"

### ISSUE THREAD

**Issue by jakubroztocil** [kevin1024/pytest-httpbin#26]
Python3 installation on Windows [fails](https://ci.appveyor.com/project/jakubroztocil/httpie/build/1.0.135/job/9t6knidopp5qxwxd#L77):

```
Reading https://pypi.python.org/simple/pytest-httpbin/
Best match: pytest-httpbin 0.0.6.macosx-10.10-x86-64
Downloading https://pypi.python.org/packages/any/p/pytest-httpbin/pytest-httpbin-0.0.6.macosx-10.10-x86_64.tar.gz#md5=c29c3895fd016dccbdb9057e33602031
Processing pytest-httpbin-0.0.6.macosx-10.10-x86_64.tar.gz
error: Couldn't find a setup script in C:\Users\appveyor\AppData\Local\Temp\easy_install-ac8isjn7\pytest-httpbin-0.0.6.macosx-10.10-x86_64.tar.gz
```

Notice that `pip` tries to install the `pytest-httpbin-0.0.6.macosx-10.10-x86_64.tar.gz` package, which according to [PyPi](https://pypi.python.org/pypi/pytest-httpbin) is a '"dumb" binary built for Darwin-14.0.0'. I think it can/should be removed from PyPi.

(Btw, there has been a similar issue with HTTPie when I accidentally published a `bdist` package: https://github.com/jakubroztocil/httpie/issues/301)

**Comment by kevin1024** [comment]
Doh my bad - meant to do bdist_wheel upload but did a bdist upload.

Will fix soon.

**Comment by kevin1024** [comment]
OK should be fixed.

**Comment by jakubroztocil** [comment]
All green again, thanks! https://ci.appveyor.com/project/jakubroztocil/httpie/build/job/2uom4d9riggiaax2
