### ISSUE TITLE
Cannot use httpbin's "stream" endpoint.

### ISSUE THREAD

**Issue by Lukasa** [kevin1024/pytest-httpbin#27]
Httpbin has an extremely useful `stream` endpoint that sends back data using chunked transfer encoding. Unfortunately, pytest-httpbin can't use it:

```
Traceback (most recent call last):
  File "/Users/cory/.pyenv/versions/2.7.10/lib/python2.7/wsgiref/handlers.py", line 85, in run
    self.result = application(self.environ, self.start_response)
  File "/Users/cory/Documents/Python/requests_org/requests/env/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/cory/Documents/Python/requests_org/requests/env/lib/python2.7/site-packages/flask/app.py", line 1821, in wsgi_app
    return response(environ, start_response)
  File "/Users/cory/Documents/Python/requests_org/requests/env/lib/python2.7/site-packages/werkzeug/wrappers.py", line 1221, in __call__
    start_response(status, headers)
  File "/Users/cory/.pyenv/versions/2.7.10/lib/python2.7/wsgiref/handlers.py", line 181, in start_response
    assert not is_hop_by_hop(name),"Hop-by-hop headers not allowed"
AssertionError: Hop-by-hop headers not allowed
127.0.0.1 - - [22/Oct/2015 11:34:56] "GET /stream/4 HTTP/1.1" 500 59
```

This is a somewhat interesting area. [PEP 333](https://www.python.org/dev/peps/pep-0333/) specifically forbids [the use of hop-by-hop headers by applications](https://www.python.org/dev/peps/pep-0333/#the-start-response-callable), so in this regard httpbin is in error (see Runscope/httpbin#259).

On the other hand, wsgiref doesn't actually know how to chunk a response, which means that the streaming iterator in this case will behave differently to the version on the web: specifically, it'll send a HTTP/1.0 length-unknown body, rather than chunked transfer encoding. This is kinda crappy on wsgiref's part, but it's arguably better than what currently happens now (a 500 error).

I think in this instance there are two possible fixes:

1. Let httpbin fix its problem and accept the HTTP/1.0 fallback.
2. Put a different WSGI server in front of pytest-httpbin that can actually handle this correctly, by emitting chunked transfer encoding. Gunicorn is what's used by the on-the-web httpbin, but uwsgi or something else would be just as suitable.

**Comment by kevin1024** [comment]
I'm not particularly happy with wsgiref. I just used it to avoid adding another dependency.

I think gunicorn uses a forking model by default currently we are running wsgiref in a thread.  I wonder if that change will affect anyone.

I saw you mention a need for multithreading.  Perhaps a switch to gunicorn could help resolve this as well.

I noticed you mentioned a need

**Comment by kevin1024** [comment]
OK, new version of httpbin is out that fixes the problem, so I'm closing this, but I'll open an issue to consider switching to gunicorn instead of wsgiref.
