### ISSUE TITLE
doesn't build from Pypi tarball

### ISSUE THREAD

**Issue by danstender** [kevin1024/pytest-httpbin#30]
Pypi tarball doesn't build:
```
$ python setup.py build
Traceback (most recent call last):
  File "setup.py", line 13, in <module>
    with codecs.open(os.path.join(here, 'DESCRIPTION.rst'), encoding='utf-8') as f:
  File "/usr/lib/python2.7/codecs.py", line 896, in open
    file = __builtin__.open(filename, mode, buffering)
IOError: [Errno 2] No such file or directory: '/tmp/sandbox/pytest-httpbin-0.1.1/DESCRIPTION.rst'
```
DESCRIPTION.rst isn't included.

BTW Debian package is coming up, httpbin is in now.

**Comment by danstender** [comment]
and ... we would like to build from Github tarballs for Debian (running tests), could you please tag according to the Pypi releases?

**Comment by kevin1024** [comment]
Just tagged latest release, sorry about that.  How cool to see it getting a Debian package!

Not sure what's up with the description file.  Currently on vacation to difficult to investigate in much detail. Happy to merge a pull to fix the build.

**Comment by danstender** [comment]
Thanks, Kevin. It builds all right with the Github tarball and going to get into NEW queue very
soon. I'll drop the info when it's accepted in the main archive.

Best,
Daniel

**Comment by kevin1024** [comment]
Great.  Not sure if it matters but requests has pytest-httpbin pinned to an older release.

**Comment by danstender** [comment]
Ah yes, o.k. Thx for the pointer, I'll check that over.

Till then,
Daniel
