### ISSUE TITLE
CPython 3.2 and PyPy 3 support

### ISSUE THREAD

**Issue by jayvdb** [kevin1024/pytest-httpbin#34]
I did a little playing around with CPython 3.2 and PyPy 3 support, mostly to determine if there are any parts of `pytest-httpbin` which `vcrpy` will not be able to use successfully on PyPy 3.  This is more of a notes dump than a request for official support, which might be useful to someone else, and can be closed if you like.

We know that at least basic PyPy 3 support is feasible, as `vcrpy` is running a lot of tests against it, and I guess support of both versions is desirable for as long as `pytest` supports both, if it doesnt cause too much pain.

httpbin doesnt support CPython 3.2, and it is unlikely to be able to while it uses `werkzeug` , which  probably will not ever support CPython 3.2 as it would mean `werkzeug` switching to `unicode_literals` and they do not seem interested in CPython 3.2.

While pypy3 isnt supported by `werkzeug`, it was trivial to get all httpbin tests to pass on pypy3, requiring only a small change (see https://github.com/Runscope/httpbin/issues/285 and https://github.com/jayvdb/httpbin/tree/pypy3) , so at least large chunks of `werkzeug` are compatible with pypy3, even if it isnt supported.

However, when using that httpbin@pypy3 , I found the `pytest-httpbin`  `test_chunked_encoding[https]` halts output from the job, which Travis then kills after 10 mins of inactivity.  See
https://travis-ci.org/jayvdb/pytest-httpbin/jobs/127127205
https://travis-ci.org/jayvdb/pytest-httpbin/builds/127128579
When I disable that test, all other tests pass.

So there shouldnt be too many problems with `vcrpy` supporting PyPy 3.
I am put a bit more time into finding the problem in `test_chunked_encoding[https]` on PyPy 3, but I'll see how I go with https://github.com/Runscope/httpbin/issues/285 first, so determine whether that is going to put a spanner in the works of PyPy 3 support.

**Comment by kevin1024** [comment]
Yeah the freezing issue has cropped up a few times.  Seems to happen when the builtin HTTP server crashes  (using wsgiref, part of the std library) crashes and none of the tests can continue.  I've seen it happen with pypy when an invalid certificate is used - pypy apparently has different behaviour than cpython when it sees an invalid SSL cert.  

https://github.com/kevin1024/pytest-httpbin/commit/61454758517a34c0e3b8051cd7bdaf412bef195e

Not sure if this issue you're seeing is related.

**Comment by kevin1024** [comment]
Possibly related to #33

**Comment by kevin1024** [comment]
Actually I wonder if it's another version of #32 you're seeing.

**Comment by graingert** [comment]
the tests are run against pypy3.7-pypy3.9 now https://github.com/kevin1024/pytest-httpbin/pull/78 and cpython 3.2 is too old to be supported
