### ISSUE TITLE
Missing git tag for 0.2.x releases

### ISSUE THREAD

**Issue by felixonmars** [kevin1024/pytest-httpbin#36]
It would be nice to keep PyPI releases and git tags in sync :)

**Comment by tari** [comment]
+1. I'm packaging for Nix and don't have a way to run tests on install because the PyPI releases don't include the tests and there aren't tags to get a source archive for the desired release from Github.

**Comment by kevin1024** [comment]
Hey @tari if I add you on as a contributor would you add the guy tags for those releases?

**Comment by kevin1024** [comment]
*git tags

**Comment by tari** [comment]
Sure, I can do that.

**Comment by kevin1024** [comment]
Thanks!  You're in.

**Comment by tari** [comment]
Cheers. :)

I've tagged the 0.2.1 through 0.2.3 releases.
