### ISSUE TITLE
Server subclassing Thread breaks Thread internals

### ISSUE THREAD

**Issue by njsmith** [kevin1024/pytest-httpbin#41]
I was trying to figure out where this really mysterious error was coming from:
```
Exception ignored in: <module 'threading' from '/usr/lib/python3.6/threading.py'>
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 1294, in _shutdown
    t.join()
TypeError: join() missing 1 required positional argument: 'url'
```

It turns out that at shutdown time, the interpreter automatically calls the `join` method on every non-daemon thread. However, pytest-httpbin's `Server` class is a `Thread` subclass that overrides the `join` method to mean something else entirely, so everyone gets very confused.

Suggested fix: instead of subclassing `Thread`, `Server` should have-a `Thread` instance.

**Comment by graingert** [comment]
Fixed in https://github.com/kevin1024/pytest-httpbin/pull/39

**Comment by njsmith** [comment]
Heh, I checked for open issues, but did not think to check for open pull requests :-)
