### ISSUE TITLE
LICENSE not present in the repo nor in the package

### ISSUE THREAD

**Issue by scarabeusiv** [kevin1024/pytest-httpbin#54]
Could you please make sure the package distributes LICENSE file (in this case MIT license copy) in the repo and in the pypi archive?
Even MIT license requires to have copy in the source code.

**Comment by graingert** [comment]
We'll probably need @kevin1024 to add the LICENCE with copyright line

**Comment by kevin1024** [comment]
Done in [0bd7637](https://github.com/kevin1024/pytest-httpbin/commit/0bd7637a5c59b1a8376b9a4f051b02a97abb8c1b)
