### ISSUE TITLE
RFE: please provide support for werkzeug 3.0.x

### ISSUE THREAD

**Issue by kloczek** [kevin1024/pytest-httpbin#84]
https://github.com/kevin1024/pytest-httpbin/blob/0bd7637a5c59b1a8376b9a4f051b02a97abb8c1b/pyproject.toml#L40-L43

**Comment by gsakkis** [comment]
Currently installing pytest-httpbin is broken:
`ImportError: cannot import name 'parse_authorization_header' from 'werkzeug.http'`

**Comment by bgb10** [comment]
@gsakkis that's because of httpbin and not an pytest-httpbin error, because httpbin used werkzeug's deprecated function. From 24.02.21, httpbin released patch for fixing those error. So that error won't happen
